# Generated by Django 5.2.4 on 2025-07-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_order_n_f3ada5_idx',
            old_name='orders_orde_order_n_87e0c5_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_retaile_66a799_idx',
            old_name='orders_orde_retaile_a55fb3_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_wholesa_6e72a3_idx',
            old_name='orders_orde_wholesa_9a53ce_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_order_d_d71205_idx',
            old_name='orders_orde_order_d_8ae8db_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c50fb7_idx',
            old_name='orders_orde_status_58da52_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_52f79a_idx',
            old_name='orders_orde_order_i_bc5de3_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_product_3ea130_idx',
            old_name='orders_orde_product_8a4b94_idx',
        ),
    ]
