# Generated by Django 5.2.5 on 2025-08-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('subtitle', models.TextField(blank=True, verbose_name='Alt başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Görsel')),
                ('link_url', models.URLField(blank=True, verbose_name='Link URL')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Link Metni')),
                ('background_color', models.CharField(default='from-primary-600 to-primary-800', max_length=50, verbose_name='Arkaplan Gradyan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Login Sayfası Banner'ı",
                'verbose_name_plural': "Login Sayfası Banner'ları",
                'ordering': ['-created_at'],
            },
        ),
    ]
