# Generated by Django 5.2.4 on 2025-07-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Özellik Adı')),
                ('attribute_type', models.CharField(choices=[('text', 'Metin'), ('number', 'Sayı'), ('boolean', 'Evet/Hayır'), ('choice', 'Seçenekli'), ('color', 'Renk'), ('size', 'Beden')], max_length=20, verbose_name='Özellik Türü')),
                ('unit', models.CharField(blank=True, help_text='Örn: cm, kg, adet', max_length=20, null=True, verbose_name='Birim')),
                ('choices', models.TextField(blank=True, help_text='Her satıra bir seçenek yazın', null=True, verbose_name='Seçenekler')),
                ('is_required', models.BooleanField(default=False, verbose_name='Zorunlu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('categories', models.ManyToManyField(blank=True, help_text='Bu özelliğin hangi kategorilerde kullanılacağı', to='products.category', verbose_name='Kategoriler')),
            ],
            options={
                'verbose_name': 'Özellik',
                'verbose_name_plural': 'Özellikler',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kısa Açıklama')),
                ('sku', models.CharField(help_text='Benzersiz ürün kodu', max_length=100, unique=True, verbose_name='Stok Kodu (SKU)')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barkod')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_digital', models.BooleanField(default=False, verbose_name='Dijital Ürün')),
                ('requires_shipping', models.BooleanField(default=True, verbose_name='Kargo Gerektirir')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Ağırlık (kg)')),
                ('dimensions_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Uzunluk (cm)')),
                ('dimensions_width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Genişlik (cm)')),
                ('dimensions_height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Yükseklik (cm)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('additional_categories', models.ManyToManyField(blank=True, related_name='additional_products', to='products.category', verbose_name='Ek Kategoriler')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Ana Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Metin Değeri')),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Sayı Değeri')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Boolean Değeri')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='products.attribute', verbose_name='Özellik')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Özellik Değeri',
                'verbose_name_plural': 'Ürün Özellik Değerleri',
                'ordering': ['attribute__sort_order', 'attribute__name'],
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
