# Generated by Django 5.2.5 on 2025-08-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery_ampere',
            field=models.CharField(blank=True, help_text='Örn: 60Ah, 74Ah, 100Ah', max_length=10, null=True, verbose_name='Akü Amperesi'),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_voltage',
            field=models.CharField(blank=True, help_text='Örn: 12V, 24V', max_length=10, null=True, verbose_name='Akü Voltajı'),
        ),
        migrations.AddField(
            model_name='product',
            name='rim_bolt_pattern',
            field=models.CharField(blank=True, help_text='Örn: 5x112, 4x100', max_length=20, null=True, verbose_name='Jant Bijon Deseni'),
        ),
        migrations.AddField(
            model_name='product',
            name='rim_size',
            field=models.CharField(blank=True, help_text='Örn: 17", 18", 19"', max_length=10, null=True, verbose_name='Jant Boyutu'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_aspect_ratio',
            field=models.CharField(blank=True, help_text='Örn: 45, 55, 65', max_length=10, null=True, verbose_name='Lastik Yan Oranı'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_diameter',
            field=models.CharField(blank=True, help_text='Örn: 17, 16, 15', max_length=10, null=True, verbose_name='Lastik Çapı'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_width',
            field=models.CharField(blank=True, help_text='Örn: 225, 205, 195', max_length=10, null=True, verbose_name='Lastik Genişliği'),
        ),
    ]
