# Generated by Django 5.2.4 on 2025-08-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='customer_management_access',
            field=models.BooleanField(default=False, help_text='Müşteri yönetim sayfasına erişebilir mi?', verbose_name='Müşteri Takibi Erişimi'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='full_dashboard_access',
            field=models.BooleanField(default=False, help_text='Tüm dashboard sayfalarına erişebilir mi?', verbose_name='Tam Dashboard Erişimi'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Ücretsiz'), ('customer_access', 'Müşteri Takibi'), ('basic', 'Temel'), ('premium', 'Premium'), ('enterprise', 'Kurumsal')], max_length=20, unique=True, verbose_name='Plan Türü'),
        ),
    ]
