# Generated by Django 5.2.4 on 2025-08-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscriptionplan_customer_management_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Planda gösterilecek özelliklerin listesi (metin olarak).",
                verbose_name="Özellikler Listesi",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="plan_type",
            field=models.CharField(
                choices=[("pro", "PRO"), ("ultra", "ULTRA")],
                max_length=20,
                unique=True,
                verbose_name="Plan Türü",
            ),
        ),
    ]
