# Generated by Django 5.2.5 on 2025-08-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('pro', 'PRO'), ('pro_plus', 'PRO PLUS'), ('ultra', 'ULTRA')], max_length=20, unique=True, verbose_name='Plan Türü'),
        ),
    ]
