# Generated by Django 5.2.5 on 2025-08-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscriptionplan_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='inventory_management_access',
            field=models.BooleanField(default=False, help_text='Envanter ve depo yönetimi sayfalarına erişebilir mi?', verbose_name='Envanter Yönetimi Erişimi'),
        ),
    ]
