# Generated by Django 5.2.4 on 2025-08-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Eski Maliyet Fiyatı",
                    ),
                ),
                (
                    "old_sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Eski Satış Fiyatı",
                    ),
                ),
                (
                    "new_cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Yeni Maliyet Fiyatı",
                    ),
                ),
                (
                    "new_sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Yeni Satış Fiyatı",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("increase", "Zam"),
                            ("decrease", "İndirim"),
                            ("set", "Fiyat Belirleme"),
                        ],
                        max_length=20,
                        verbose_name="Değişiklik Türü",
                    ),
                ),
                (
                    "change_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Yüzde olarak değişiklik miktarı",
                        max_digits=5,
                        null=True,
                        verbose_name="Değişiklik Yüzdesi",
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Sabit tutar olarak değişiklik miktarı",
                        max_digits=12,
                        null=True,
                        verbose_name="Değişiklik Tutarı",
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        help_text="Değişikliği yapan kullanıcının adı",
                        max_length=200,
                        verbose_name="Değiştiren Kişi",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True,
                        help_text="Fiyat değişikliğinin açıklaması",
                        null=True,
                        verbose_name="Değişiklik Nedeni",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="inventory.stockitem",
                        verbose_name="Stok Kalemi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiyat Geçmişi",
                "verbose_name_plural": "Fiyat Geçmişleri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stock_item", "-created_at"],
                        name="inventory_p_stock_i_155246_idx",
                    ),
                    models.Index(
                        fields=["change_type"], name="inventory_p_change__245a1d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="inventory_p_created_075122_idx"
                    ),
                ],
            },
        ),
    ]
