# Generated by Django 5.2.5 on 2025-08-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='barcode',
            field=models.CharField(blank=True, help_text='Stok kalemi için özel barkod', max_length=100, null=True, verbose_name='Barkod'),
        ),
    ]
