# Generated by Django 5.2.5 on 2025-08-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerwholesaler',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bu toptancıdan alınan ürünlerde uygulanacak iskonto oranı (örneğin, 5.00 için %5)', max_digits=5, verbose_name='İskonto Oranı'),
        ),
    ]
