# Generated by Django 5.2.4 on 2025-07-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Kullanıcının bağlı olduğu şirket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company', verbose_name='Şirket'),
        ),
    ]
